apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-cluster
  namespace: argocd

spec:
  project: mongodb

  source:
    repoURL: https://github.com/naikabhi11/gitops-repo
    targetRevision: main
    path: apps/mongodb

  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
