apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd

spec:
  project: mongodb

  source:
    repoURL: https://github.com/naikabhi11/gitops-repo
    targetRevision: main
    path: operators/mongodb

  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
